# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

# monitor=,addreserved, 0, 0, 0, 0 # Custom reserved area

# HDMI port: mirror display. To see device name, use `hyprctl monitors`


device {
    name = realtek-mchose-l7-ultra+
    sensitivity = -0.5
    accel_profile = flat
}